/**
 * This class is generated by jOOQ
 */
package de.isnow.stypesafe.jooq.tables;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = {"http://www.jooq.org", "2.5.1"},
                            comments = "This class is generated by jOOQ")
public class Activitylog extends org.jooq.impl.UpdatableTableImpl<de.isnow.stypesafe.jooq.tables.records.ActivitylogRecord> {

	private static final long serialVersionUID = -840386427;

	/**
	 * The singleton instance of stypesafe.activitylog
	 */
	public static final de.isnow.stypesafe.jooq.tables.Activitylog ACTIVITYLOG = new de.isnow.stypesafe.jooq.tables.Activitylog();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<de.isnow.stypesafe.jooq.tables.records.ActivitylogRecord> getRecordType() {
		return de.isnow.stypesafe.jooq.tables.records.ActivitylogRecord.class;
	}

	/**
	 * The table column <code>stypesafe.activitylog.id</code>
	 * <p>
	 * This column is part of the table's PRIMARY KEY
	 */
	public final org.jooq.TableField<de.isnow.stypesafe.jooq.tables.records.ActivitylogRecord, org.jooq.tools.unsigned.UInteger> ID = createField("id", org.jooq.impl.SQLDataType.INTEGERUNSIGNED, this);

	/**
	 * The table column <code>stypesafe.activitylog.timestamp</code>
	 */
	public final org.jooq.TableField<de.isnow.stypesafe.jooq.tables.records.ActivitylogRecord, java.sql.Timestamp> TIMESTAMP = createField("timestamp", org.jooq.impl.SQLDataType.TIMESTAMP, this);

	/**
	 * The table column <code>stypesafe.activitylog.activity</code>
	 */
	public final org.jooq.TableField<de.isnow.stypesafe.jooq.tables.records.ActivitylogRecord, java.lang.String> ACTIVITY = createField("activity", org.jooq.impl.SQLDataType.VARCHAR, this);

	/**
	 * The table column <code>stypesafe.activitylog.result</code>
	 */
	public final org.jooq.TableField<de.isnow.stypesafe.jooq.tables.records.ActivitylogRecord, java.lang.String> RESULT = createField("result", org.jooq.impl.SQLDataType.VARCHAR, this);

	public Activitylog() {
		super("activitylog", de.isnow.stypesafe.jooq.Stypesafe.STYPESAFE);
	}

	public Activitylog(java.lang.String alias) {
		super(alias, de.isnow.stypesafe.jooq.Stypesafe.STYPESAFE, de.isnow.stypesafe.jooq.tables.Activitylog.ACTIVITYLOG);
	}

	@Override
	public org.jooq.Identity<de.isnow.stypesafe.jooq.tables.records.ActivitylogRecord, org.jooq.tools.unsigned.UInteger> getIdentity() {
		return de.isnow.stypesafe.jooq.Keys.IDENTITY_ACTIVITYLOG;
	}

	@Override
	public org.jooq.UniqueKey<de.isnow.stypesafe.jooq.tables.records.ActivitylogRecord> getMainKey() {
		return de.isnow.stypesafe.jooq.Keys.KEY_ACTIVITYLOG_PRIMARY;
	}

	@Override
	@SuppressWarnings("unchecked")
	public java.util.List<org.jooq.UniqueKey<de.isnow.stypesafe.jooq.tables.records.ActivitylogRecord>> getKeys() {
		return java.util.Arrays.<org.jooq.UniqueKey<de.isnow.stypesafe.jooq.tables.records.ActivitylogRecord>>asList(de.isnow.stypesafe.jooq.Keys.KEY_ACTIVITYLOG_PRIMARY);
	}

	@Override
	public de.isnow.stypesafe.jooq.tables.Activitylog as(java.lang.String alias) {
		return new de.isnow.stypesafe.jooq.tables.Activitylog(alias);
	}
}
