/**
 * This class is generated by jOOQ
 */
package de.isnow.stypesafe.jooq.tables;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = {"http://www.jooq.org", "2.5.1"},
                            comments = "This class is generated by jOOQ")
public class Author extends org.jooq.impl.UpdatableTableImpl<de.isnow.stypesafe.jooq.tables.records.AuthorRecord> {

	private static final long serialVersionUID = 1116910344;

	/**
	 * The singleton instance of stypesafe.author
	 */
	public static final de.isnow.stypesafe.jooq.tables.Author AUTHOR = new de.isnow.stypesafe.jooq.tables.Author();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<de.isnow.stypesafe.jooq.tables.records.AuthorRecord> getRecordType() {
		return de.isnow.stypesafe.jooq.tables.records.AuthorRecord.class;
	}

	/**
	 * The table column <code>stypesafe.author.id</code>
	 * <p>
	 * This column is part of the table's PRIMARY KEY
	 */
	public final org.jooq.TableField<de.isnow.stypesafe.jooq.tables.records.AuthorRecord, org.jooq.tools.unsigned.UInteger> ID = createField("id", org.jooq.impl.SQLDataType.INTEGERUNSIGNED, this);

	/**
	 * The table column <code>stypesafe.author.stypiuid</code>
	 */
	public final org.jooq.TableField<de.isnow.stypesafe.jooq.tables.records.AuthorRecord, java.lang.String> STYPIUID = createField("stypiuid", org.jooq.impl.SQLDataType.VARCHAR, this);

	/**
	 * The table column <code>stypesafe.author.username</code>
	 */
	public final org.jooq.TableField<de.isnow.stypesafe.jooq.tables.records.AuthorRecord, java.lang.String> USERNAME = createField("username", org.jooq.impl.SQLDataType.VARCHAR, this);

	public Author() {
		super("author", de.isnow.stypesafe.jooq.Stypesafe.STYPESAFE);
	}

	public Author(java.lang.String alias) {
		super(alias, de.isnow.stypesafe.jooq.Stypesafe.STYPESAFE, de.isnow.stypesafe.jooq.tables.Author.AUTHOR);
	}

	@Override
	public org.jooq.Identity<de.isnow.stypesafe.jooq.tables.records.AuthorRecord, org.jooq.tools.unsigned.UInteger> getIdentity() {
		return de.isnow.stypesafe.jooq.Keys.IDENTITY_AUTHOR;
	}

	@Override
	public org.jooq.UniqueKey<de.isnow.stypesafe.jooq.tables.records.AuthorRecord> getMainKey() {
		return de.isnow.stypesafe.jooq.Keys.KEY_AUTHOR_PRIMARY;
	}

	@Override
	@SuppressWarnings("unchecked")
	public java.util.List<org.jooq.UniqueKey<de.isnow.stypesafe.jooq.tables.records.AuthorRecord>> getKeys() {
		return java.util.Arrays.<org.jooq.UniqueKey<de.isnow.stypesafe.jooq.tables.records.AuthorRecord>>asList(de.isnow.stypesafe.jooq.Keys.KEY_AUTHOR_PRIMARY);
	}

	@Override
	public de.isnow.stypesafe.jooq.tables.Author as(java.lang.String alias) {
		return new de.isnow.stypesafe.jooq.tables.Author(alias);
	}
}
