/**
 * This class is generated by jOOQ
 */
package de.isnow.stypesafe.jooq.tables;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = {"http://www.jooq.org", "2.5.1"},
                            comments = "This class is generated by jOOQ")
public class Documentfragment extends org.jooq.impl.UpdatableTableImpl<de.isnow.stypesafe.jooq.tables.records.DocumentfragmentRecord> {

	private static final long serialVersionUID = 1794036861;

	/**
	 * The singleton instance of stypesafe.documentfragment
	 */
	public static final de.isnow.stypesafe.jooq.tables.Documentfragment DOCUMENTFRAGMENT = new de.isnow.stypesafe.jooq.tables.Documentfragment();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<de.isnow.stypesafe.jooq.tables.records.DocumentfragmentRecord> getRecordType() {
		return de.isnow.stypesafe.jooq.tables.records.DocumentfragmentRecord.class;
	}

	/**
	 * The table column <code>stypesafe.documentfragment.id</code>
	 * <p>
	 * This column is part of the table's PRIMARY KEY
	 */
	public final org.jooq.TableField<de.isnow.stypesafe.jooq.tables.records.DocumentfragmentRecord, org.jooq.tools.unsigned.UInteger> ID = createField("id", org.jooq.impl.SQLDataType.INTEGERUNSIGNED, this);

	/**
	 * The table column <code>stypesafe.documentfragment.text</code>
	 */
	public final org.jooq.TableField<de.isnow.stypesafe.jooq.tables.records.DocumentfragmentRecord, java.lang.String> TEXT = createField("text", org.jooq.impl.SQLDataType.CLOB, this);

	/**
	 * The table column <code>stypesafe.documentfragment.fingerprint</code>
	 */
	public final org.jooq.TableField<de.isnow.stypesafe.jooq.tables.records.DocumentfragmentRecord, java.lang.String> FINGERPRINT = createField("fingerprint", org.jooq.impl.SQLDataType.VARCHAR, this);

	public Documentfragment() {
		super("documentfragment", de.isnow.stypesafe.jooq.Stypesafe.STYPESAFE);
	}

	public Documentfragment(java.lang.String alias) {
		super(alias, de.isnow.stypesafe.jooq.Stypesafe.STYPESAFE, de.isnow.stypesafe.jooq.tables.Documentfragment.DOCUMENTFRAGMENT);
	}

	@Override
	public org.jooq.Identity<de.isnow.stypesafe.jooq.tables.records.DocumentfragmentRecord, org.jooq.tools.unsigned.UInteger> getIdentity() {
		return de.isnow.stypesafe.jooq.Keys.IDENTITY_DOCUMENTFRAGMENT;
	}

	@Override
	public org.jooq.UniqueKey<de.isnow.stypesafe.jooq.tables.records.DocumentfragmentRecord> getMainKey() {
		return de.isnow.stypesafe.jooq.Keys.KEY_DOCUMENTFRAGMENT_PRIMARY;
	}

	@Override
	@SuppressWarnings("unchecked")
	public java.util.List<org.jooq.UniqueKey<de.isnow.stypesafe.jooq.tables.records.DocumentfragmentRecord>> getKeys() {
		return java.util.Arrays.<org.jooq.UniqueKey<de.isnow.stypesafe.jooq.tables.records.DocumentfragmentRecord>>asList(de.isnow.stypesafe.jooq.Keys.KEY_DOCUMENTFRAGMENT_PRIMARY);
	}

	@Override
	public de.isnow.stypesafe.jooq.tables.Documentfragment as(java.lang.String alias) {
		return new de.isnow.stypesafe.jooq.tables.Documentfragment(alias);
	}
}
