/**
 * This class is generated by jOOQ
 */
package de.isnow.stypesafe.jooq.tables;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = {"http://www.jooq.org", "2.5.1"},
                            comments = "This class is generated by jOOQ")
public class Error extends org.jooq.impl.UpdatableTableImpl<de.isnow.stypesafe.jooq.tables.records.ErrorRecord> {

	private static final long serialVersionUID = -1911944378;

	/**
	 * The singleton instance of stypesafe.error
	 */
	public static final de.isnow.stypesafe.jooq.tables.Error ERROR = new de.isnow.stypesafe.jooq.tables.Error();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<de.isnow.stypesafe.jooq.tables.records.ErrorRecord> getRecordType() {
		return de.isnow.stypesafe.jooq.tables.records.ErrorRecord.class;
	}

	/**
	 * The table column <code>stypesafe.error.id</code>
	 * <p>
	 * This column is part of the table's PRIMARY KEY
	 */
	public final org.jooq.TableField<de.isnow.stypesafe.jooq.tables.records.ErrorRecord, org.jooq.tools.unsigned.UInteger> ID = createField("id", org.jooq.impl.SQLDataType.INTEGERUNSIGNED, this);

	/**
	 * The table column <code>stypesafe.error.timestamp</code>
	 */
	public final org.jooq.TableField<de.isnow.stypesafe.jooq.tables.records.ErrorRecord, java.sql.Timestamp> TIMESTAMP = createField("timestamp", org.jooq.impl.SQLDataType.TIMESTAMP, this);

	/**
	 * The table column <code>stypesafe.error.error</code>
	 */
	public final org.jooq.TableField<de.isnow.stypesafe.jooq.tables.records.ErrorRecord, java.lang.String> ERROR_ = createField("error", org.jooq.impl.SQLDataType.VARCHAR, this);

	public Error() {
		super("error", de.isnow.stypesafe.jooq.Stypesafe.STYPESAFE);
	}

	public Error(java.lang.String alias) {
		super(alias, de.isnow.stypesafe.jooq.Stypesafe.STYPESAFE, de.isnow.stypesafe.jooq.tables.Error.ERROR);
	}

	@Override
	public org.jooq.Identity<de.isnow.stypesafe.jooq.tables.records.ErrorRecord, org.jooq.tools.unsigned.UInteger> getIdentity() {
		return de.isnow.stypesafe.jooq.Keys.IDENTITY_ERROR;
	}

	@Override
	public org.jooq.UniqueKey<de.isnow.stypesafe.jooq.tables.records.ErrorRecord> getMainKey() {
		return de.isnow.stypesafe.jooq.Keys.KEY_ERROR_PRIMARY;
	}

	@Override
	@SuppressWarnings("unchecked")
	public java.util.List<org.jooq.UniqueKey<de.isnow.stypesafe.jooq.tables.records.ErrorRecord>> getKeys() {
		return java.util.Arrays.<org.jooq.UniqueKey<de.isnow.stypesafe.jooq.tables.records.ErrorRecord>>asList(de.isnow.stypesafe.jooq.Keys.KEY_ERROR_PRIMARY);
	}

	@Override
	public de.isnow.stypesafe.jooq.tables.Error as(java.lang.String alias) {
		return new de.isnow.stypesafe.jooq.tables.Error(alias);
	}
}
