/**
 * This class is generated by jOOQ
 */
package de.isnow.stypesafe.jooq.tables;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = {"http://www.jooq.org", "2.5.1"},
                            comments = "This class is generated by jOOQ")
public class Fragmentxversion extends org.jooq.impl.UpdatableTableImpl<de.isnow.stypesafe.jooq.tables.records.FragmentxversionRecord> {

	private static final long serialVersionUID = -926167529;

	/**
	 * The singleton instance of stypesafe.fragmentXversion
	 */
	public static final de.isnow.stypesafe.jooq.tables.Fragmentxversion FRAGMENTXVERSION = new de.isnow.stypesafe.jooq.tables.Fragmentxversion();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<de.isnow.stypesafe.jooq.tables.records.FragmentxversionRecord> getRecordType() {
		return de.isnow.stypesafe.jooq.tables.records.FragmentxversionRecord.class;
	}

	/**
	 * The table column <code>stypesafe.fragmentXversion.id</code>
	 * <p>
	 * This column is part of the table's PRIMARY KEY
	 */
	public final org.jooq.TableField<de.isnow.stypesafe.jooq.tables.records.FragmentxversionRecord, org.jooq.tools.unsigned.UInteger> ID = createField("id", org.jooq.impl.SQLDataType.INTEGERUNSIGNED, this);

	/**
	 * The table column <code>stypesafe.fragmentXversion.fk_documentversion</code>
	 * <p>
	 * This column is part of a FOREIGN KEY: <code><pre>
	 * CONSTRAINT version
	 * FOREIGN KEY (fk_documentversion)
	 * REFERENCES stypesafe.documentversion (id)
	 * </pre></code>
	 */
	public final org.jooq.TableField<de.isnow.stypesafe.jooq.tables.records.FragmentxversionRecord, org.jooq.tools.unsigned.UInteger> FK_DOCUMENTVERSION = createField("fk_documentversion", org.jooq.impl.SQLDataType.INTEGERUNSIGNED, this);

	/**
	 * The table column <code>stypesafe.fragmentXversion.fk_documentfragment</code>
	 * <p>
	 * This column is part of a FOREIGN KEY: <code><pre>
	 * CONSTRAINT fragment
	 * FOREIGN KEY (fk_documentfragment)
	 * REFERENCES stypesafe.documentfragment (id)
	 * </pre></code>
	 */
	public final org.jooq.TableField<de.isnow.stypesafe.jooq.tables.records.FragmentxversionRecord, org.jooq.tools.unsigned.UInteger> FK_DOCUMENTFRAGMENT = createField("fk_documentfragment", org.jooq.impl.SQLDataType.INTEGERUNSIGNED, this);

	/**
	 * The table column <code>stypesafe.fragmentXversion.fk_author</code>
	 * <p>
	 * This column is part of a FOREIGN KEY: <code><pre>
	 * CONSTRAINT author
	 * FOREIGN KEY (fk_author)
	 * REFERENCES stypesafe.author (id)
	 * </pre></code>
	 */
	public final org.jooq.TableField<de.isnow.stypesafe.jooq.tables.records.FragmentxversionRecord, org.jooq.tools.unsigned.UInteger> FK_AUTHOR = createField("fk_author", org.jooq.impl.SQLDataType.INTEGERUNSIGNED, this);

	public Fragmentxversion() {
		super("fragmentXversion", de.isnow.stypesafe.jooq.Stypesafe.STYPESAFE);
	}

	public Fragmentxversion(java.lang.String alias) {
		super(alias, de.isnow.stypesafe.jooq.Stypesafe.STYPESAFE, de.isnow.stypesafe.jooq.tables.Fragmentxversion.FRAGMENTXVERSION);
	}

	@Override
	public org.jooq.Identity<de.isnow.stypesafe.jooq.tables.records.FragmentxversionRecord, org.jooq.tools.unsigned.UInteger> getIdentity() {
		return de.isnow.stypesafe.jooq.Keys.IDENTITY_FRAGMENTXVERSION;
	}

	@Override
	public org.jooq.UniqueKey<de.isnow.stypesafe.jooq.tables.records.FragmentxversionRecord> getMainKey() {
		return de.isnow.stypesafe.jooq.Keys.KEY_FRAGMENTXVERSION_PRIMARY;
	}

	@Override
	@SuppressWarnings("unchecked")
	public java.util.List<org.jooq.UniqueKey<de.isnow.stypesafe.jooq.tables.records.FragmentxversionRecord>> getKeys() {
		return java.util.Arrays.<org.jooq.UniqueKey<de.isnow.stypesafe.jooq.tables.records.FragmentxversionRecord>>asList(de.isnow.stypesafe.jooq.Keys.KEY_FRAGMENTXVERSION_PRIMARY);
	}

	@Override
	@SuppressWarnings("unchecked")
	public java.util.List<org.jooq.ForeignKey<de.isnow.stypesafe.jooq.tables.records.FragmentxversionRecord, ?>> getReferences() {
		return java.util.Arrays.<org.jooq.ForeignKey<de.isnow.stypesafe.jooq.tables.records.FragmentxversionRecord, ?>>asList(de.isnow.stypesafe.jooq.Keys.VERSION, de.isnow.stypesafe.jooq.Keys.FRAGMENT, de.isnow.stypesafe.jooq.Keys.AUTHOR);
	}

	@Override
	public de.isnow.stypesafe.jooq.tables.Fragmentxversion as(java.lang.String alias) {
		return new de.isnow.stypesafe.jooq.tables.Fragmentxversion(alias);
	}
}
