/**
 * This class is generated by jOOQ
 */
package de.isnow.stypesafe.jooq.tables.records;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = {"http://www.jooq.org", "2.5.1"},
                            comments = "This class is generated by jOOQ")
public class ActivitylogRecord extends org.jooq.impl.UpdatableRecordImpl<de.isnow.stypesafe.jooq.tables.records.ActivitylogRecord> {

	private static final long serialVersionUID = -294692700;

	/**
	 * The table column <code>stypesafe.activitylog.id</code>
	 * <p>
	 * This column is part of the table's PRIMARY KEY
	 */
	public void setId(org.jooq.tools.unsigned.UInteger value) {
		setValue(de.isnow.stypesafe.jooq.tables.Activitylog.ACTIVITYLOG.ID, value);
	}

	/**
	 * The table column <code>stypesafe.activitylog.id</code>
	 * <p>
	 * This column is part of the table's PRIMARY KEY
	 */
	public org.jooq.tools.unsigned.UInteger getId() {
		return getValue(de.isnow.stypesafe.jooq.tables.Activitylog.ACTIVITYLOG.ID);
	}

	/**
	 * The table column <code>stypesafe.activitylog.timestamp</code>
	 */
	public void setTimestamp(java.sql.Timestamp value) {
		setValue(de.isnow.stypesafe.jooq.tables.Activitylog.ACTIVITYLOG.TIMESTAMP, value);
	}

	/**
	 * The table column <code>stypesafe.activitylog.timestamp</code>
	 */
	public java.sql.Timestamp getTimestamp() {
		return getValue(de.isnow.stypesafe.jooq.tables.Activitylog.ACTIVITYLOG.TIMESTAMP);
	}

	/**
	 * The table column <code>stypesafe.activitylog.activity</code>
	 */
	public void setActivity(java.lang.String value) {
		setValue(de.isnow.stypesafe.jooq.tables.Activitylog.ACTIVITYLOG.ACTIVITY, value);
	}

	/**
	 * The table column <code>stypesafe.activitylog.activity</code>
	 */
	public java.lang.String getActivity() {
		return getValue(de.isnow.stypesafe.jooq.tables.Activitylog.ACTIVITYLOG.ACTIVITY);
	}

	/**
	 * The table column <code>stypesafe.activitylog.result</code>
	 */
	public void setResult(java.lang.String value) {
		setValue(de.isnow.stypesafe.jooq.tables.Activitylog.ACTIVITYLOG.RESULT, value);
	}

	/**
	 * The table column <code>stypesafe.activitylog.result</code>
	 */
	public java.lang.String getResult() {
		return getValue(de.isnow.stypesafe.jooq.tables.Activitylog.ACTIVITYLOG.RESULT);
	}

	/**
	 * Create a detached ActivitylogRecord
	 */
	public ActivitylogRecord() {
		super(de.isnow.stypesafe.jooq.tables.Activitylog.ACTIVITYLOG);
	}
}
