/**
 * This class is generated by jOOQ
 */
package de.isnow.stypesafe.jooq.tables.records;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = {"http://www.jooq.org", "2.5.1"},
                            comments = "This class is generated by jOOQ")
public class AuthorRecord extends org.jooq.impl.UpdatableRecordImpl<de.isnow.stypesafe.jooq.tables.records.AuthorRecord> {

	private static final long serialVersionUID = 2051737484;

	/**
	 * The table column <code>stypesafe.author.id</code>
	 * <p>
	 * This column is part of the table's PRIMARY KEY
	 */
	public void setId(org.jooq.tools.unsigned.UInteger value) {
		setValue(de.isnow.stypesafe.jooq.tables.Author.AUTHOR.ID, value);
	}

	/**
	 * The table column <code>stypesafe.author.id</code>
	 * <p>
	 * This column is part of the table's PRIMARY KEY
	 */
	public org.jooq.tools.unsigned.UInteger getId() {
		return getValue(de.isnow.stypesafe.jooq.tables.Author.AUTHOR.ID);
	}

	/**
	 * The table column <code>stypesafe.author.id</code>
	 * <p>
	 * This column is part of the table's PRIMARY KEY
	 */
	public java.util.List<de.isnow.stypesafe.jooq.tables.records.FragmentxversionRecord> fetchFragmentxversionList() {
		return create()
			.selectFrom(de.isnow.stypesafe.jooq.tables.Fragmentxversion.FRAGMENTXVERSION)
			.where(de.isnow.stypesafe.jooq.tables.Fragmentxversion.FRAGMENTXVERSION.FK_AUTHOR.equal(getValue(de.isnow.stypesafe.jooq.tables.Author.AUTHOR.ID)))
			.fetch();
	}

	/**
	 * The table column <code>stypesafe.author.stypiuid</code>
	 */
	public void setStypiuid(java.lang.String value) {
		setValue(de.isnow.stypesafe.jooq.tables.Author.AUTHOR.STYPIUID, value);
	}

	/**
	 * The table column <code>stypesafe.author.stypiuid</code>
	 */
	public java.lang.String getStypiuid() {
		return getValue(de.isnow.stypesafe.jooq.tables.Author.AUTHOR.STYPIUID);
	}

	/**
	 * The table column <code>stypesafe.author.username</code>
	 */
	public void setUsername(java.lang.String value) {
		setValue(de.isnow.stypesafe.jooq.tables.Author.AUTHOR.USERNAME, value);
	}

	/**
	 * The table column <code>stypesafe.author.username</code>
	 */
	public java.lang.String getUsername() {
		return getValue(de.isnow.stypesafe.jooq.tables.Author.AUTHOR.USERNAME);
	}

	/**
	 * Create a detached AuthorRecord
	 */
	public AuthorRecord() {
		super(de.isnow.stypesafe.jooq.tables.Author.AUTHOR);
	}
}
