/**
 * This class is generated by jOOQ
 */
package de.isnow.stypesafe.jooq.tables.records;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = {"http://www.jooq.org", "2.5.1"},
                            comments = "This class is generated by jOOQ")
public class DocumentfragmentRecord extends org.jooq.impl.UpdatableRecordImpl<de.isnow.stypesafe.jooq.tables.records.DocumentfragmentRecord> {

	private static final long serialVersionUID = 328634254;

	/**
	 * The table column <code>stypesafe.documentfragment.id</code>
	 * <p>
	 * This column is part of the table's PRIMARY KEY
	 */
	public void setId(org.jooq.tools.unsigned.UInteger value) {
		setValue(de.isnow.stypesafe.jooq.tables.Documentfragment.DOCUMENTFRAGMENT.ID, value);
	}

	/**
	 * The table column <code>stypesafe.documentfragment.id</code>
	 * <p>
	 * This column is part of the table's PRIMARY KEY
	 */
	public org.jooq.tools.unsigned.UInteger getId() {
		return getValue(de.isnow.stypesafe.jooq.tables.Documentfragment.DOCUMENTFRAGMENT.ID);
	}

	/**
	 * The table column <code>stypesafe.documentfragment.id</code>
	 * <p>
	 * This column is part of the table's PRIMARY KEY
	 */
	public java.util.List<de.isnow.stypesafe.jooq.tables.records.FragmentxversionRecord> fetchFragmentxversionList() {
		return create()
			.selectFrom(de.isnow.stypesafe.jooq.tables.Fragmentxversion.FRAGMENTXVERSION)
			.where(de.isnow.stypesafe.jooq.tables.Fragmentxversion.FRAGMENTXVERSION.FK_DOCUMENTFRAGMENT.equal(getValue(de.isnow.stypesafe.jooq.tables.Documentfragment.DOCUMENTFRAGMENT.ID)))
			.fetch();
	}

	/**
	 * The table column <code>stypesafe.documentfragment.text</code>
	 */
	public void setText(java.lang.String value) {
		setValue(de.isnow.stypesafe.jooq.tables.Documentfragment.DOCUMENTFRAGMENT.TEXT, value);
	}

	/**
	 * The table column <code>stypesafe.documentfragment.text</code>
	 */
	public java.lang.String getText() {
		return getValue(de.isnow.stypesafe.jooq.tables.Documentfragment.DOCUMENTFRAGMENT.TEXT);
	}

	/**
	 * The table column <code>stypesafe.documentfragment.fingerprint</code>
	 */
	public void setFingerprint(java.lang.String value) {
		setValue(de.isnow.stypesafe.jooq.tables.Documentfragment.DOCUMENTFRAGMENT.FINGERPRINT, value);
	}

	/**
	 * The table column <code>stypesafe.documentfragment.fingerprint</code>
	 */
	public java.lang.String getFingerprint() {
		return getValue(de.isnow.stypesafe.jooq.tables.Documentfragment.DOCUMENTFRAGMENT.FINGERPRINT);
	}

	/**
	 * Create a detached DocumentfragmentRecord
	 */
	public DocumentfragmentRecord() {
		super(de.isnow.stypesafe.jooq.tables.Documentfragment.DOCUMENTFRAGMENT);
	}
}
