/**
 * This class is generated by jOOQ
 */
package de.isnow.stypesafe.jooq.tables.records;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = {"http://www.jooq.org", "2.5.1"},
                            comments = "This class is generated by jOOQ")
public class ErrorRecord extends org.jooq.impl.UpdatableRecordImpl<de.isnow.stypesafe.jooq.tables.records.ErrorRecord> {

	private static final long serialVersionUID = -852537262;

	/**
	 * The table column <code>stypesafe.error.id</code>
	 * <p>
	 * This column is part of the table's PRIMARY KEY
	 */
	public void setId(org.jooq.tools.unsigned.UInteger value) {
		setValue(de.isnow.stypesafe.jooq.tables.Error.ERROR.ID, value);
	}

	/**
	 * The table column <code>stypesafe.error.id</code>
	 * <p>
	 * This column is part of the table's PRIMARY KEY
	 */
	public org.jooq.tools.unsigned.UInteger getId() {
		return getValue(de.isnow.stypesafe.jooq.tables.Error.ERROR.ID);
	}

	/**
	 * The table column <code>stypesafe.error.timestamp</code>
	 */
	public void setTimestamp(java.sql.Timestamp value) {
		setValue(de.isnow.stypesafe.jooq.tables.Error.ERROR.TIMESTAMP, value);
	}

	/**
	 * The table column <code>stypesafe.error.timestamp</code>
	 */
	public java.sql.Timestamp getTimestamp() {
		return getValue(de.isnow.stypesafe.jooq.tables.Error.ERROR.TIMESTAMP);
	}

	/**
	 * The table column <code>stypesafe.error.error</code>
	 */
	public void setError(java.lang.String value) {
		setValue(de.isnow.stypesafe.jooq.tables.Error.ERROR.ERROR_, value);
	}

	/**
	 * The table column <code>stypesafe.error.error</code>
	 */
	public java.lang.String getError() {
		return getValue(de.isnow.stypesafe.jooq.tables.Error.ERROR.ERROR_);
	}

	/**
	 * Create a detached ErrorRecord
	 */
	public ErrorRecord() {
		super(de.isnow.stypesafe.jooq.tables.Error.ERROR);
	}
}
