/**
 * This class is generated by jOOQ
 */
package de.isnow.stypesafe.jooq.tables.records;

import java.sql.Timestamp;

import org.jooq.impl.UpdatableRecordImpl;
import org.jooq.tools.unsigned.UInteger;

import de.isnow.stypesafe.jooq.tables.Error;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = {"http://www.jooq.org", "2.4.2"},
                            comments = "This class is generated by jOOQ")
public class ErrorRecord extends UpdatableRecordImpl<ErrorRecord> {

	private static final long serialVersionUID = 2096258066;

	/**
	 * The table column <code>stypesafe.error.id</code>
	 * <p>
	 * This column is part of the table's PRIMARY KEY
	 */
	public void setId(UInteger value) {
		setValue(Error.ERROR.ID, value);
	}

	/**
	 * The table column <code>stypesafe.error.id</code>
	 * <p>
	 * This column is part of the table's PRIMARY KEY
	 */
	public UInteger getId() {
		return getValue(Error.ERROR.ID);
	}

	/**
	 * The table column <code>stypesafe.error.timestamp</code>
	 */
	public void setTimestamp(Timestamp value) {
		setValue(Error.ERROR.TIMESTAMP, value);
	}

	/**
	 * The table column <code>stypesafe.error.timestamp</code>
	 */
	public Timestamp getTimestamp() {
		return getValue(Error.ERROR.TIMESTAMP);
	}

	/**
	 * The table column <code>stypesafe.error.error</code>
	 */
	public void setError(String value) {
		setValue(Error.ERROR.ERROR_, value);
	}

	/**
	 * The table column <code>stypesafe.error.error</code>
	 */
	public String getError() {
		return getValue(Error.ERROR.ERROR_);
	}

	/**
	 * Create a detached ErrorRecord
	 */
	public ErrorRecord() {
		super(Error.ERROR);
	}
}
