/**
 * This class is generated by jOOQ
 */
package de.isnow.stypesafe.jooq;

import java.util.Arrays;
import java.util.List;

import org.jooq.impl.SchemaImpl;

import de.isnow.stypesafe.jooq.tables.Author;
import de.isnow.stypesafe.jooq.tables.Document;
import de.isnow.stypesafe.jooq.tables.Documentfragment;
import de.isnow.stypesafe.jooq.tables.Documentversion;
import de.isnow.stypesafe.jooq.tables.Error;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = {"http://www.jooq.org", "2.4.2"},
                            comments = "This class is generated by jOOQ")
public class Stypesafe extends SchemaImpl {

	private static final long serialVersionUID = -1673559339;

	/**
	 * The singleton instance of stypesafe
	 */
	public static final Stypesafe STYPESAFE = new Stypesafe();

	/**
	 * No further instances allowed
	 */
	private Stypesafe() {
		super("stypesafe");
	}

	@Override
	public final List<org.jooq.Table<?>> getTables() {
		return Arrays.<org.jooq.Table<?>>asList(
			Author.AUTHOR,
			Document.DOCUMENT,
			Documentfragment.DOCUMENTFRAGMENT,
			Documentversion.DOCUMENTVERSION,
			Error.ERROR);
	}
}
