/**
 * This class is generated by jOOQ
 */
package de.isnow.stypesafe.jooq;

import de.isnow.stypesafe.jooq.tables.Author;
import de.isnow.stypesafe.jooq.tables.Document;
import de.isnow.stypesafe.jooq.tables.Documentfragment;
import de.isnow.stypesafe.jooq.tables.Documentversion;
import de.isnow.stypesafe.jooq.tables.Error;

/**
 * This class is generated by jOOQ.
 *
 * Convenience access to all tables in stypesafe
 */
@javax.annotation.Generated(value    = {"http://www.jooq.org", "2.4.2"},
                            comments = "This class is generated by jOOQ")
public final class Tables {

	/**
	 * The table stypesafe.author
	 */
	public static final Author AUTHOR = Author.AUTHOR;

	/**
	 * The table stypesafe.document
	 */
	public static final Document DOCUMENT = Document.DOCUMENT;

	/**
	 * The table stypesafe.documentfragment
	 */
	public static final Documentfragment DOCUMENTFRAGMENT = Documentfragment.DOCUMENTFRAGMENT;

	/**
	 * The table stypesafe.documentversion
	 */
	public static final Documentversion DOCUMENTVERSION = Documentversion.DOCUMENTVERSION;

	/**
	 * The table stypesafe.error
	 */
	public static final Error ERROR = Error.ERROR;

}
